repos:
  # basic hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: detect-private-key

  # Python format/lint - use ruff for both to avoid conflicts
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.18.2
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         - pydantic>=2
  #         - types-requests

  # security scanning(simple) - temporarily disabled for hackathon
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.8.6
  #   hooks:
  #     - id: bandit
  #       args: ["-r", "api/", "-lll", "-x", "api/tests/", "-x", "api/db/"]
  #       files: ^api/.*\.py$

  # frontend format(Prettier)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^app/(src|.*)\.(ts|tsx|js|jsx|json|css|md)$
