version: '3.8'

services:
  # Backend API
  api:
    build: .
    ports:
      - "8082:8082"
    environment:
      - DB_URL=sqlite:///./api/copilot.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEMO_ACCESS_CODE=${DEMO_ACCESS_CODE:-demo123}
      - DEMO_MODE=true
      - HIPAA_MODE=false
      - enable_rag=true
    volumes:
      - ./data:/app/data:ro
      - ./api/reports:/app/api/reports
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend (development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8082
    depends_on:
      - api
    restart: unless-stopped

  # Database (optional - for production)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: bbb_medical
  #     POSTGRES_USER: bbb_user
  #     POSTGRES_PASSWORD: bbb_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  postgres_data:
